
OBJECT_PAGE = 'page'
MESSAGE_DATA_OBJECT = 'object'
MESSAGE_DATA_ENTRY = 'entry'
PAGE_ENTRY_MESSAGING = 'messaging'

EVENT_OPTIN = 'optin'
EVENT_MESSAGE = 'message'
EVENT_DELIVERY = 'delivery'
EVENT_POSTBACK = 'postback'
EVENT_READ = 'read'
EVENT_ACCOUNT_LINKING = 'account_linking'

ATTACHMENT_TYPE_IMAGE = 'image'
ATTACHMENT_TYPE_AUDIO = 'audio'
ATTACHMENT_TYPE_VIDEO = 'video'
ATTACHMENT_TYPE_FILE = 'file'

SENDER_ACTION_MARK_SEEN = 'mark_seen'
SENDER_ACTION_TYPING_ON = 'typing_on'
SENDER_ACTION_TYPING_OFF = 'typing_off'
